export const enum GroupEnumAugment {
  BASIC = "Basic",
  FUSED = "Fused",
  DUALBLE = "Dualble",
  WARD = "Ward",
  SOUL = "Soul",
  NOTE = "Note",
  DOMINA = "Domina",
  SECRETA = "Secreta",
  DREAD = "Dread",
  GIGAS = "Gigas",
  EXPLOIT = "Exploit",
  FUSIA = "Fusia",
  ADDI = "Addi",
  TRIA = "Tria",
  DECOLD = "Decold",
  SEZUN = "Sezun",
  SUPER = "Super",
  INALE = "Inale",
}
